[[footer]]
name = "About"
url = "about/"
weight = 2
[[footer]]
name = "Publications"
url = "project/"
weight = 3
[[footer]]
name = "Contact"
url = "contact/"
weight = 7
[[main]]
name = "Home"
url = ""
weight = 1
[[main]]
name = "About"
url = "about/"
weight = 2
[[main]]
name = "Publications"
url = "project/"
weight = 3
[[main]]
name = "Blog"
url = "blog/"
weight = 4
[[main]]
name = "IHIWS"
parent = "More"
url = "faq/"
weight = "5"
[[main]]
name = "Contact"
url = "contact/"
weight = "6"
